### PR TITLE
Maeloni lesson backend

### PR DESCRIPTION
**Pull request by Mae830**
Add lessons to the backend. Also added testing for the lessons. Lessons can have multiple select questions, multiple choice, text, code, or images.

### CODE REVIEW

**Comment by marcgabe15** [comment]
It seems like the npm install script is failing on CI, are you able to npm install cleanly? and what version of node are you working on? @Mae830

**Comment by marcgabe15** [comment]
Why did package-lock.json change? I don't see any dependencies added.

**Comment by marcgabe15** [comment]
please run npm audit fix

**Review by marcgabe15 — APPROVED** [review]

**Review by kapooramanpreet — APPROVED** [review]
LGTM!

**Pull request merged**
