### PR TITLE
Fix models and authentication

### PR DESCRIPTION
**Pull request by dhruv2000**
Fixed .populate problem

### CODE REVIEW

**Review by HamishPierpont — DISMISSED** [review]
LGTM

**Comment by dhruv2000** [comment]
This is the important pull request for authentication and getting .populate to work

**Review by AqSlz — APPROVED** [review]
LGTM

**Review by HamishPierpont — APPROVED** [review]
LGTM

**Review by AqSlz — APPROVED** [review]

**Review by AqSlz — APPROVED** [review]

**Pull request merged**
