### PR TITLE
fix error middlewares

### PR DESCRIPTION
**Pull request by marcgabe15**
# Description
What does this PR do? It adds error middleware for the express routing

# Related Issue
N/A
# Motivation and Context
This allows for better logging

# How Has This Been Tested?
N/A

# Screenshots (if appropriate):

### CODE REVIEW

**Review by HamishPierpont — DISMISSED** [review]
LGTM - assuming the import error that caused the CI check to fail is fixed

**Review by HamishPierpont — APPROVED** [review]
LGTM

**Review by dhruv2000 — APPROVED** [review]
LGTM

**Review by dhruv2000 — DISMISSED** [review]
LGTM

**Review by HamishPierpont — APPROVED** [review]
LGTM

**Review by dhruv2000 — APPROVED** [review]
LGTM

**Pull request merged**
